---
- name: Install Required Packages 
  apt: 
    name:
      - mysql-server 
      - php-fpm
      - php-mysql 
      - unzip 
      - wget
      - python3-pymysql
    state: present 
    update_cache: yes 
- name: Start and enable mysql 
  service: 
    name: mysql 
    state: restarted 
    enabled: yes
- name: Secure MySQL root user (change authentication to password-based)
  mysql_user:
    name: "{{wp_db_user}}"
    host: "%"
    password: "{{ wp_db_password }}"  # Replace with your desired root password
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:ALL,GRANT"
    state: present
- name: Create MySQL Database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: "{{wp_db_user}}"
    login_password: "{{ wp_db_password }}"
  become: no
- name: Create MySQL User
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: "{{wp_db_user}}"
    login_password: "{{ wp_db_password }}"
  become: no
- name: Ensure /var/www/html exists
  file:
    path: "{{ doc_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: yes
- name: Download and extract wordpress
  get_url:
    url: "{{wp_url}}"
    dest: /tmp/wordpress.tar.gz 
- name: Extract Wordpress 
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{doc_root}}"
    remote_src: yes 
    extra_opts: [--strip-components=1]
- name: Set permissions for wp 
  file:
    path: "{{doc_root}}"
    owner: www-data 
    group: www-data 
    mode: "0755"
    recurse: yes 
- name: Configure wp-config.php 
  template: 
    src: wp-config.php.j2 
    dest: "{{ doc_root }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: "0644"