---
- hosts: localhost 
  connection: local
  tasks:
  - name: creating ec2 instance 
    amazon.aws.ec2_instance:
      name: "ansible_instance"
      instance_type: "t3.micro"
      region: "ap-south-1"
      security_group: "default"
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      network: 
        assign_public_ip: true 
      image_id: "ami-00bb6a80f01f03502"
      tags: 
        Name: Test_EC2